version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
      - dbvol:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: webapp
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp

  webapp:
    depends_on:
      - db
    build: .

    ports:
      - "80:80"

    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: webapp
      DATABASE_USER: webapp
      DATABASE_PASSWORD: webapp
      DATABASE_HOST: db
      DATABASE_PORT: 3306

volumes:
  dbvol: